.TH STRESS-TEST "1" "2008-06-24" "Freegeek Extras" "User Commands"
.SH NAME
basiccheck - run's through a series of tests
.SH SYNOPSIS
.BR basiccheck
[OPTIONS...] [TESTS...]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
displays a help message
.TP
\fB\-d\fR, \fB\-\-debug\fR
turn debugging on (don't use)
.TP
\fB\-C\fR, \fB\-\-color\fR
Make things colorful
.TP
\fB\-m\fR, \fB\-\-menu\fR
Gives you a menu with a list of tests to choose from.
.TP
\fB\-s\fR, \fB\-\-show-tests\fR
Lists all of the available tests
.SH NOTES
By default it will go through all the tests.


.\"Usage: ./basiccheck [options] [tests ...]
.\"    -h, --help                       Show this message
.\"    -d, --debug                      Turn debugging on
.\"    -C, --color                      Enable coloration of the output
.\"    -m, --menu                       Create a menu for test selection
.\"    -s, --show-tests                 Show a list of available tests
