.TH PRINTME "1" "2008-05-22" "Freegeek Extras" "User Commands"
.SH NAME 
printme - Send system information to our database and you get back a report
.SH SYNOPSIS
.BR printme
[\fB\-p\fR
printer]
.SH DESCRIPTION
Printme can only be ran when you are plugged into freegeek's build network. It will ask you questions about what type of system this is, what you did to it, and who you are. It will then collect data about the system's hardware and send all of this information to our database. If everything works properly, firefox will open up with a printable report.
.TP
\fB\-p\fR printer, \fB\-\-printer\fR printer
Print to the named printer
.SH BUGS
If you discover a bug, tell a build instructor. If you are a build instructor, please email the buildteachers email list.
.SH AUTHORS
Ryan Niebur <RyanRyan52@gmail.com>
.br
Martin Chase
.SH SEE ALSO
.BR basiccheck (1),
.BR magix (1)
