.TH STRESS-TEST "1" "2008-05-22" "Freegeek Extras" "User Commands"
.SH NAME
stress-test - runs a 3 minute stress test
.SH SYNOPSIS
.BR stress-test
[\fB-h\fR|\fB\-v\fR|\fB\-q\fR]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
displays a help message
.TP
\fB\-v\fR, \fB\-\-verbose\fR
runs stress in verbose mode
.TP
\fB\-q\fR, \fB\-\-quiet\fR
runs stress in quiet mode, this is the default
.SH NOTES
This will take 3 minutes

