#!/bin/sh

sed -i '/freegeek-extras/d' /etc/cups/cupsd.conf
sed -i '/freegeek-extras/d' /etc/cups/lpoptions
sed -i '/freegeek-extras/d' /etc/cups/printers.conf

if [ -f /etc/hostname_freekbox ]; then
    HNAME=`hostname`
    ORIG="$(cat /etc/hostname_freekbox)"
    if [ "$HNAME" = 'freekbox' ] && [ ! -z "$ORIG" ]; then
        hostname "$ORIG"
        rm /etc/hostname_freekbox
        echo "$ORIG" > /etc/hostname
        sed -i "s/$HNAME/$ORIG/g" /etc/hosts
    fi
fi

#DEBHELPER#
