#!/bin/sh

substitute_release(){
    sources_list_file=$1
    release=$2
    sed -e "s,RELEASE,$release,g" $sources_list_file
}

list_file='freekbox.list'
dest_list_dir='debian/'

mkdir -p $dest_list_dir

# generate entries for LTS releases
for dist in dapper hardy lucid; do
    substitute_release $list_file $dist > $dest_list_dir/$dist.list
done
