#!/bin/sh

TEMPDIR=`mktemp -d`
for i in $(
    for i in $(ls /sys/block/)
    do udevinfo --query all --name $i > $TEMPDIR/$i
        if grep -q "E: ID_TYPE=cd" $TEMPDIR/$i; then
            printf "$i "
        fi
    done); do
    TEMPFILE=$TEMPDIR/$i
    /usr/lib/freegeek_show_cd_drives.awk < $TEMPFILE
    echo
done
rm -fr $TEMPDIR
