#!/bin/sh

PATH=$PATH:/sbin

myudevinfo() {
    if which udevadm >/dev/null; then
        udevadm info $@
    elif which udevinfo >/dev/null; then
        udevinfo $@
    else
        echo "Can't find udevinfo" >&2
        exit 1
    fi
}

TEMPDIR=`mktemp -d`
for i in $(
    for i in $(ls /sys/block/ | grep -v "^dm-"); do
        myudevinfo --query all --name $i > $TEMPDIR/$i
        if grep -q "E: ID_TYPE=cd" $TEMPDIR/$i; then
            printf "$i "
        fi
    done); do
    TEMPFILE=$TEMPDIR/$i
    /usr/lib/freegeek_show_cd_drives.awk < $TEMPFILE
    echo
done
rm -fr $TEMPDIR
