#!/usr/bin/env python

#Copyright: Free Geek (2005)
#	    python rewrite of 10reboots.sh by Doughnut and vagrant cascadian
#	    chopped down to 4reboots by dave and the distro group
#License: GPL v2 or any later version
#	  On Debian GNU/Linux systems, the complete text of the GNU General
#	  Public License (GPL) can be found below /usr/share/common-licenses/
#	  or check it out at http://www.gnu.org/licenses/gpl.html

# puts a bunch of files into a startup directory which force the system to
# reboot a bunch of times -- used to stress test the hardware

import os, sys

number_reboots=4

if os.geteuid() != 0 :
   print "This script must be run with root privilages."
   print "Use the command \"su\" to do this."
   print "Exiting..."
   sys.exit()
   
message="""
4reboots scripts installed...
type "sudo reboot" to begin the reboot process
pay attention to any weird behaviour as it's rebooting.
"""

# bash script to generate
shellscript="""#!/bin/bash
rm -f $0
echo "reboot %s of %s"
sleep 3
init 6"""

for current_reboot in xrange(number_reboots):
  filename='/etc/rcS.d/S99z_reboot_%s_of_%s' % (current_reboot, number_reboots)
  x=open(filename, 'w')
  x.write(shellscript % (current_reboot+1, number_reboots))
  x.close()
  os.system('chmod +x %s' % filename)

print message
