#!/bin/bash
if [ -z "$1" ]; then
    echo "usage: $0 file"
    exit 1 
fi
if [ $(id -u) != 0 ]; then 
    sudo $0 "$@"
    exit $?
fi
TMPFILE=$(mktemp -d /tmp/example.XXXXXXXXXX) || exit 1
GRUB=/boot/grub/menu.lst
cp "$1" $TMPFILE 
#change to a temp directory
cd $TMPFILE 
#make a directory to hold DOS image
mkdir -p /boot/dos/
#copy memdisk 
cp /usr/lib/syslinux/memdisk /boot/dos/
#get DOS image	(hopefully link remains stable)
wget http://www.fdos.org/bootdisks/autogen/FDOEM.144.gz
gzip -d -c FDOEM.144.gz > /boot/dos/FDOEM.144
#backup and modify mtools.conf
#cp /etc/mtools.conf /etc/mtools.conf.bak
perl -pi.bak -e 's,drive b: file="/dev/fd1" exclusive,drive b: file="/boot/dos/FDOEM.144",' /etc/mtools.conf
#copy bios image to dos floppy image
mcopy $(basename $1) b:

cp $GRUB ${GRUB}.bak
if ! grep -q "Bios Flasher" /boot/grub/menu.lst; then
    if grep -q /boot /boot/grub/menu.lst; then 
	cat<<EOF >>$GRUB

title	Bios Flasher
kernel	/boot/dos/memdisk
initrd	/boot/dos/FDOEM.144

EOF
    else
	cat<<EOF >>$GRUB

title	Bios Flasher
kernel	/dos/memdisk
initrd	/dos/FDOEM.144

EOF
    fi    
fi