#!/bin/sh

#Daniel's DVD wiping script.

CODE=1

while true; do
  echo -n "Would you like to attempt blanking the DVD now? "
  read BLANK
  if echo "$BLANK" | grep -i '^n' > /dev/null ; then
    echo "You have chosen not to blank the DVD now."
    echo "Exiting."
    break
  elif echo "$BLANK" | grep -i '^y' > /dev/null ; then
    echo "You have chosen to blank the DVD."
    echo "Press enter to continue.."
    read
    clear
    dvd+rw-format -force /dev/dvd
    CODE="$?"
    echo
    echo "Your DVD should now be blank."
    echo "Please check that the DVD is blank."
    echo "If it's not, try rerunning $(basename $0)"
    echo "or talk to your friendly Build Instructor."
    break
  else
    echo "Invalid response \"$BLANK\", please answer either yes or no."
  fi
done

exit $CODE
