#!/usr/bin/ruby

require 'printme'

def mymain
  file = Tempfile.new("list-printmes")
  runit(file.path)
  newfile = File.open(file.path)
  @lshw_output = newfile.read
  newfile.close
  file.close
  File.unlink(newfile.path)
  @detected_system_id = @driver.get_system_id(@lshw_output)
  look_at_url(@driver.system_url(@detected_system_id))
end

main
