#!/bin/bash

case "$1" in
  start) ;;
  stop) exit 0 ;;
  restart) exit 0 ;;
  force-reload) exit 0 ;;
esac

OLD_DIR="/tmp/old_home"
mkdir -p $OLD_DIR
cd /home

for i in $(echo * | grep -ve '^oem'); do
  deluser $i
  mv -f $i $OLD_DIR/$i
done

exec /etc/init.d/oem-config start
